Repository microsoft/mu_oem_sample, pull requests merged in 2023-07, with the labels that each got.

#116 HelloUefi init
  OemPkg/HelloUefi/HelloUefi.c
  OemPkg/HelloUefi/HelloUefi.inf
  OemPkg/HelloUefi/HelloUefi.ver
  OemPkg/OemPkg.dsc
Labels: impact:non-functional

#117 OemPkg/HelloUefi - CI fixes
  OemPkg/HelloUefi/HelloUefi.c
  OemPkg/HelloUefi/HelloUefi.inf
  OemPkg/HelloUefi/HelloUefi.ver
  OemPkg/OemPkg.dsc
Labels: impact:non-functional

#120 HelloUefi: Add 30 second stall
  OemPkg/HelloUefi/HelloUefi.c
  OemPkg/HelloUefi/HelloUefi.inf
  OemPkg/HelloUefi/Readme.md
Labels: type:documentation, impact:non-functional

#121 OemPkg: Fix build
  OemPkg/HelloUefi/HelloUefi.c
  OemPkg/HelloUefi/Readme.md
  OemPkg/OemPkg.ci.yaml
Labels: type:bug, impact:non-functional
