Repository microsoft/mu_oem_sample, pull requests merged in 2024-01, with the labels that each got.

#175 .git-blame-ignore-revs: Ignore Line Ending and Uncrustify only commits
  .git-blame-ignore-revs
Labels: impact:non-functional, semver:patch

#183 Update pip-requirements.txt
  pip-requirements.txt
Labels: type:dependencies

#178 Updated CISettings.py to use the edk2toolext codeql helpers
  .github/workflows/codeql.yml
  .pytool/CISettings.py
Labels: impact:testing, impact:non-functional
